updated pre-commit and pre-push hooks to print out meaningful error messages
[EasyCI] tests passed

diff --git a/easyci/hooks/pre-commit b/easyci/hooks/pre-commit
--- a/easyci/hooks/pre-commit
+++ b/easyci/hooks/pre-commit
@@ -1,3 +1,10 @@
 #!/bin/bash
 
 eci test --staged-only
+
+CODE=$?
+
+if [ $CODE -ne 0 ]; then
+    echo 'Tests failed. To commit anyways, run `git commit --no-verify`.'
+    exit $CODE
+fi
diff --git a/easyci/hooks/pre-push b/easyci/hooks/pre-push
--- a/easyci/hooks/pre-push
+++ b/easyci/hooks/pre-push
@@ -1,3 +1,10 @@
 #!/bin/bash
 
 eci test --head-only
+
+CODE=$?
+
+if [ $CODE -ne 0 ]; then
+    echo 'Tests failed. To push anyways, run `git push --no-verify`.'
+    exit $CODE
+fi
